name: upload my image to DockerHub
# CI 
on:
  push:
    branches: [ main ]
jobs:
  build: #מייצר איימג׳ מחדש ודוחף אותו לדוקר האב
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create docker image
        run: echo Hello, world!

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/calculator-test:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/calculator-test:latest
        
# כאשר יש שינוי בקוד רוצים שהוא ימחק את הקונטיינר הקודם יצור חדש ויריץ
  deploy: #  עושה אסאסאיץ׳ לשרת שלי 
   needs: build #תרוץ בטור
   runs-on: ubuntu-latest
   steps:
     - name: deploy app
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USER }}
         key: ${{ secrets.PRIVATE_KEY }}
         port: ${{ secrets.PORT }}
         script_stop: true
         script: |
           sudo docker stop calc-test
           sudo docker rm calc-test
           sudo docker rmi gilcolman/calculator-test
           sudo docker pull gilcolman/calculator-test
           sudo docker run --name calc -d -p 80:3000 gilcolman/calculator-test
